#!/bin/bash

# Check if the input file is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <input_file>"
    exit 1
fi

input_file="$1"

# Extract the host or IP address column and count occurrences
cut -f 1 "$input_file" | sort | uniq -c | sort -nr | head -n 11 | awk '{print $2}' 
